hangman = [
    """
  +---+
  |   |
      |
      |
      |
      |
=========""",
    """
  +---+
  |   |
  O   |
      |
      |
      |
=========""",
    """
  +---+
  |   |
  O   |
  |   |
      |
      |
=========""",
    """
  +---+
  |   |
  O   |
 /|   |
      |
      |
=========""",
    """
  +---+
  |   |
  O   |
 /|\\  |
      |
      |
=========""",
    """
  +---+
  |   |
  O   |
 /|\\  |
 /    |
      |
=========""",
    """
  +---+
  |   |
  O   |
 /|\\  |
 / \\  |
      |
=========""",
]

sentences = [
    "Penyanyi terkenal asyik bermain sepeda baru dengan sangat hati-hati.",
    "Pedagang kaki lima sedang membaca kamera digital karena ingin memberi kejutan.",
    "Pedagang kaki lima tengah melukis piring terbang di halaman belakang rumah.",
    "Penulis novel sedang menunggu kamera digital di atas meja makan.",
    "Pemain bola sangat menyukai surat rahasia di pinggir pantai yang indah.",
    "Robot canggih rajin membersihkan lampu taman dengan menggunakan alat khusus.",
    "Koki handal ingin meminjam lukisan abstrak di halaman belakang rumah.",
    "Penyanyi terkenal sangat menyukai bunga mawar dengan sangat hati-hati.",
    "Dokter gigi selalu membawa lampu taman bersama teman-teman sekolah.",
    "Kupu-kupu indah sedang memasak sepeda baru sepanjang jalan kenangan.",
    "Robot canggih selalu membawa layang-layang untuk persiapan ujian nasional.",
    "Robot canggih rajin membersihkan pohon mangga di bawah sinar rembulan.",
    "Dokter gigi sedang membaca pohon mangga di toko buku terdekat.",
    "Nelayan tua sedang mencari kunci inggris di pinggir pantai yang indah.",
    "Dokter gigi berhasil menemukan piring terbang di dalam perpustakaan kota.",
    "Robot canggih sudah membeli gitar listrik di atas meja makan.",
    "Nelayan tua tengah melukis pohon mangga pada pagi hari yang cerah.",
    "Penulis novel telah menyelesaikan lampu taman di pinggir pantai yang indah.",
    "Penyanyi terkenal telah menyelesaikan buku sejarah untuk persiapan ujian nasional.",
    "Murid teladan akan menjual buku sejarah di halaman belakang rumah.",
    "Presiden direktur rajin membersihkan lukisan abstrak sepanjang jalan kenangan.",
    "Pemain bola diam-diam memakan boneka beruang karena ingin memberi kejutan.",
    "Supir bus berhasil menemukan radio antik bersama teman-teman sekolah.",
    "Dokter gigi asyik bermain layang-layang di lapangan sepak bola.",
    "Pedagang kaki lima sedang membaca surat rahasia dengan sangat hati-hati.",
    "Burung hantu selalu membawa sepeda baru di pinggir pantai yang indah.",
    "Anjing penjaga sedang memperbaiki topi sulap di atas meja makan.",
    "Penyanyi terkenal sedang memperbaiki mobil balap di bawah sinar rembulan.",
    "Burung hantu terlihat mengamati pohon mangga sebelum matahari terbenam.",
    "Murid teladan selalu membawa jam dinding pada pagi hari yang cerah.",
    "Anjing penjaga sedang menunggu buku sejarah di bawah sinar rembulan.",
    "Adik saya berhasil menemukan komputer jinjing untuk persiapan ujian nasional.",
    "Burung hantu asyik bermain jam dinding di dalam perpustakaan kota.",
    "Presiden direktur sedang membaca buku sejarah pada pagi hari yang cerah.",
    "Pedagang kaki lima sedang mencari sepatu roda saat hujan turun deras.",
    "Kupu-kupu indah sangat menyukai gitar listrik dengan perasaan gembira.",
    "Koki handal telah menyelesaikan gitar listrik di toko buku terdekat.",
    "Burung hantu sangat menyukai layang-layang saat hujan turun deras.",
    "Kakak perempuan sedang menunggu sepeda baru di lapangan sepak bola.",
    "Kakak perempuan sedang mencari topi sulap di toko buku terdekat.",
    "Robot canggih sangat menyukai komputer jinjing di pinggir pantai yang indah.",
    "Kupu-kupu indah sedang membaca bunga mawar karena merasa sangat lapar.",
    "Koki handal sedang memasak topi sulap karena ingin memberi kejutan.",
    "Seorang guru berusaha menangkap bunga mawar dengan menggunakan alat khusus.",
    "Murid teladan sedang mencari lampu taman saat hujan turun deras.",
    "Adik saya sedang memasak jam dinding di bawah sinar rembulan.",
    "Kupu-kupu indah sangat menyukai pohon mangga di dalam perpustakaan kota.",
    "Dokter gigi berusaha menangkap mobil balap tanpa sepengetahuan siapapun.",
    "Anjing penjaga berhasil menemukan mobil balap di bawah sinar rembulan.",
    "Seorang guru akan menjual lampu taman sepanjang jalan kenangan.",
    "Burung hantu rajin membersihkan lampu taman di atas meja makan.",
    "Adik saya berusaha menangkap topi sulap saat hujan turun deras.",
    "Penulis novel sangat menyukai kamera digital di toko buku terdekat.",
    "Robot canggih sangat menyukai lukisan abstrak sebelum matahari terbenam.",
    "Anjing penjaga diam-diam memakan jam dinding dengan sangat hati-hati.",
    "Pemain bola tengah melukis layang-layang bersama teman-teman sekolah.",
    "Penulis novel sedang membaca lampu taman karena ingin memberi kejutan.",
    "Polisi tidur akan menjual mobil balap di halaman belakang rumah.",
    "Dokter gigi baru saja menanam jam dinding di pinggir pantai yang indah.",
    "Burung hantu sedang memasak lampu taman saat hujan turun deras.",
    "Nelayan tua terlihat mengamati sepeda baru untuk persiapan ujian nasional.",
    "Polisi tidur sedang memasak layang-layang di dalam perpustakaan kota.",
    "Anjing penjaga rajin membersihkan kamera digital di tengah hutan belantara.",
    "Pemain bola rajin membersihkan topi sulap di dalam perpustakaan kota.",
    "Penyanyi terkenal terlihat mengamati lampu taman di toko buku terdekat.",
    "Kakak perempuan rajin membersihkan lampu taman di pinggir pantai yang indah.",
    "Kakak perempuan sedang memperbaiki boneka beruang karena merasa sangat lapar.",
    "Kakak perempuan tidak sengaja menjatuhkan surat rahasia di bawah sinar rembulan.",
    "Pemain bola tidak sengaja menjatuhkan sepatu roda dengan menggunakan alat khusus.",
    "Koki handal sedang memperbaiki layang-layang di pinggir pantai yang indah.",
    "Nelayan tua sedang memasak komputer jinjing untuk persiapan ujian nasional.",
    "Murid teladan terlihat mengamati boneka beruang dengan sangat hati-hati.",
    "Koki handal tidak sengaja menjatuhkan radio antik karena merasa sangat lapar.",
    "Presiden direktur berhasil menemukan piring terbang karena merasa sangat lapar.",
    "Adik saya sedang membaca sepeda baru karena merasa sangat lapar.",
    "Kakak perempuan tengah melukis mobil balap di bawah sinar rembulan.",
    "Presiden direktur sangat menyukai sepatu roda untuk persiapan ujian nasional.",
    "Kakak perempuan tengah melukis surat rahasia sepanjang jalan kenangan.",
    "Penyanyi terkenal ingin meminjam gitar listrik pada pagi hari yang cerah.",
    "Penulis novel tidak sengaja menjatuhkan pohon mangga di dalam perpustakaan kota.",
    "Pemain bola diam-diam memakan surat rahasia sepanjang jalan kenangan.",
    "Supir bus rajin membersihkan kunci inggris untuk persiapan ujian nasional.",
    "Penulis novel baru saja menanam gitar listrik di bawah sinar rembulan.",
    "Kucing tetangga akan menjual gitar listrik dengan perasaan gembira.",
    "Penyanyi terkenal berusaha menangkap buku sejarah bersama teman-teman sekolah.",
    "Pemain bola baru saja menanam surat rahasia di toko buku terdekat.",
    "Presiden direktur diam-diam memakan sepeda baru di dalam perpustakaan kota.",
    "Pemain bola tidak sengaja menjatuhkan kunci inggris di lapangan sepak bola.",
    "Penulis novel rajin membersihkan mobil balap sepanjang jalan kenangan.",
    "Presiden direktur sangat menyukai topi sulap karena ingin memberi kejutan.",
    "Supir bus sedang memasak lampu taman pada pagi hari yang cerah.",
    "Kucing tetangga sedang memperbaiki boneka beruang bersama teman-teman sekolah.",
    "Kupu-kupu indah tidak sengaja menjatuhkan kamera digital di bawah sinar rembulan.",
    "Burung hantu tengah melukis mobil balap di dalam perpustakaan kota.",
    "Anjing penjaga berusaha menangkap sepatu roda dengan perasaan gembira.",
    "Seorang guru terlihat mengamati kunci inggris dengan sangat hati-hati.",
    "Kucing tetangga sangat menyukai lukisan abstrak di atas meja makan.",
    "Kupu-kupu indah sedang menunggu lukisan abstrak di tengah hutan belantara.",
    "Pemain bola sedang menunggu boneka beruang di dalam perpustakaan kota.",
    "Seorang guru sedang mencari sepatu roda di pinggir pantai yang indah.",
    "Burung hantu tengah melukis boneka beruang di toko buku terdekat.",
    "Kakak perempuan terlihat mengamati komputer jinjing di dalam perpustakaan kota.",
    "Presiden direktur sedang memperbaiki topi sulap dengan perasaan gembira.",
    "Anjing penjaga asyik bermain komputer jinjing di pinggir pantai yang indah.",
    "Pemain bola rajin membersihkan gitar listrik dengan perasaan gembira.",
    "Kupu-kupu indah berhasil menemukan jam dinding di halaman belakang rumah.",
    "Murid teladan telah menyelesaikan mobil balap di dalam perpustakaan kota.",
    "Presiden direktur sedang menunggu gitar listrik saat hujan turun deras.",
    "Murid teladan sangat menyukai buku sejarah dengan perasaan gembira.",
    "Dokter gigi asyik bermain pohon mangga pada pagi hari yang cerah.",
    "Murid teladan terlihat mengamati layang-layang karena ingin memberi kejutan.",
    "Koki handal sudah membeli sepatu roda untuk persiapan ujian nasional.",
    "Robot canggih berhasil menemukan radio antik dengan menggunakan alat khusus.",
    "Burung hantu baru saja menanam mobil balap pada pagi hari yang cerah.",
    "Seorang guru sedang memperbaiki mobil balap di toko buku terdekat.",
    "Penyanyi terkenal berusaha menangkap surat rahasia karena merasa sangat lapar.",
    "Nelayan tua telah menyelesaikan layang-layang di lapangan sepak bola.",
    "Koki handal sedang membaca piring terbang saat hujan turun deras.",
    "Kucing tetangga tidak sengaja menjatuhkan layang-layang di bawah sinar rembulan.",
    "Seorang guru selalu membawa topi sulap di pinggir pantai yang indah.",
    "Dokter gigi baru saja menanam gitar listrik di pinggir pantai yang indah.",
    "Pemain bola berusaha menangkap boneka beruang dengan sangat hati-hati.",
    "Pedagang kaki lima sangat menyukai layang-layang tanpa sepengetahuan siapapun.",
    "Pemain bola rajin membersihkan layang-layang pada pagi hari yang cerah.",
    "Presiden direktur sedang mencari boneka beruang sepanjang jalan kenangan.",
    "Polisi tidur asyik bermain radio antik di halaman belakang rumah.",
    "Supir bus akan menjual radio antik di pinggir pantai yang indah.",
    "Robot canggih telah menyelesaikan surat rahasia sebelum matahari terbenam.",
    "Penulis novel sangat menyukai lampu taman tanpa sepengetahuan siapapun.",
    "Robot canggih sudah membeli kunci inggris tanpa sepengetahuan siapapun.",
    "Para petani telah menyelesaikan bunga mawar dengan perasaan gembira.",
    "Penyanyi terkenal tengah melukis sepeda baru di tengah hutan belantara.",
    "Supir bus sudah membeli sepeda baru sebelum matahari terbenam.",
    "Penulis novel ingin meminjam mobil balap dengan sangat hati-hati.",
    "Para petani sedang mencari bunga mawar karena ingin memberi kejutan.",
    "Burung hantu telah menyelesaikan gitar listrik dengan perasaan gembira.",
    "Polisi tidur sedang memperbaiki surat rahasia di halaman belakang rumah.",
    "Pedagang kaki lima ingin meminjam lampu taman sebelum matahari terbenam.",
    "Supir bus diam-diam memakan sepeda baru bersama teman-teman sekolah.",
    "Kupu-kupu indah diam-diam memakan nasi goreng di halaman belakang rumah.",
    "Para petani sedang menunggu kamera digital di tengah hutan belantara.",
    "Murid teladan ingin meminjam nasi goreng karena ingin memberi kejutan.",
    "Nelayan tua tengah melukis gitar listrik di pinggir pantai yang indah.",
    "Robot canggih ingin meminjam mobil balap di halaman belakang rumah.",
    "Dokter gigi selalu membawa jam dinding sebelum matahari terbenam.",
    "Pemain bola tidak sengaja menjatuhkan lukisan abstrak sepanjang jalan kenangan.",
    "Murid teladan sedang menunggu layang-layang sebelum matahari terbenam.",
    "Burung hantu sedang mencari sepeda baru saat hujan turun deras.",
    "Dokter gigi sedang mencari lukisan abstrak di lapangan sepak bola.",
    "Nelayan tua sedang memperbaiki gitar listrik karena ingin memberi kejutan.",
    "Nelayan tua telah menyelesaikan gitar listrik dengan sangat hati-hati.",
    "Koki handal ingin meminjam mobil balap di dalam perpustakaan kota.",
    "Anjing penjaga ingin meminjam jam dinding dengan perasaan gembira.",
    "Dokter gigi sedang menunggu kamera digital di dalam perpustakaan kota.",
    "Anjing penjaga sedang menunggu sepatu roda karena ingin memberi kejutan.",
    "Robot canggih diam-diam memakan layang-layang dengan menggunakan alat khusus.",
    "Kupu-kupu indah selalu membawa komputer jinjing dengan sangat hati-hati.",
    "Anjing penjaga tengah melukis jam dinding sepanjang jalan kenangan.",
    "Robot canggih asyik bermain mobil balap dengan menggunakan alat khusus.",
    "Adik saya rajin membersihkan radio antik sepanjang jalan kenangan.",
    "Burung hantu sudah membeli kunci inggris untuk persiapan ujian nasional.",
    "Adik saya tengah melukis layang-layang untuk persiapan ujian nasional.",
    "Supir bus berusaha menangkap sepeda baru saat hujan turun deras.",
    "Presiden direktur sedang menunggu layang-layang di dalam perpustakaan kota.",
    "Burung hantu sangat menyukai kunci inggris di tengah hutan belantara.",
    "Penyanyi terkenal sedang membaca jam dinding di lapangan sepak bola.",
    "Dokter gigi selalu membawa nasi goreng dengan perasaan gembira.",
    "Koki handal sedang memperbaiki radio antik di halaman belakang rumah.",
    "Penyanyi terkenal ingin meminjam radio antik di lapangan sepak bola.",
    "Koki handal berusaha menangkap pohon mangga di dalam perpustakaan kota.",
    "Kucing tetangga baru saja menanam sepatu roda di bawah sinar rembulan.",
    "Koki handal sedang membaca lukisan abstrak di tengah hutan belantara.",
    "Robot canggih ingin meminjam komputer jinjing di bawah sinar rembulan.",
    "Polisi tidur sedang menunggu sepeda baru saat hujan turun deras.",
    "Adik saya berhasil menemukan mobil balap pada pagi hari yang cerah.",
    "Kucing tetangga rajin membersihkan gitar listrik dengan perasaan gembira.",
    "Presiden direktur asyik bermain layang-layang dengan menggunakan alat khusus.",
    "Robot canggih rajin membersihkan topi sulap karena ingin memberi kejutan.",
    "Dokter gigi telah menyelesaikan nasi goreng pada pagi hari yang cerah.",
    "Burung hantu telah menyelesaikan surat rahasia dengan sangat hati-hati.",
    "Kupu-kupu indah sedang mencari sepeda baru di toko buku terdekat.",
    "Penulis novel berusaha menangkap piring terbang di toko buku terdekat.",
    "Dokter gigi sedang memperbaiki kunci inggris di toko buku terdekat.",
    "Supir bus tidak sengaja menjatuhkan lukisan abstrak dengan sangat hati-hati.",
    "Pedagang kaki lima sedang membaca komputer jinjing pada pagi hari yang cerah.",
    "Dokter gigi terlihat mengamati kunci inggris karena ingin memberi kejutan.",
    "Adik saya baru saja menanam nasi goreng untuk persiapan ujian nasional.",
    "Penyanyi terkenal sudah membeli kamera digital di lapangan sepak bola.",
    "Robot canggih tengah melukis sepeda baru di bawah sinar rembulan.",
    "Murid teladan tidak sengaja menjatuhkan layang-layang saat hujan turun deras.",
    "Para petani diam-diam memakan pohon mangga pada pagi hari yang cerah.",
    "Dokter gigi diam-diam memakan bunga mawar sebelum matahari terbenam.",
    "Kucing tetangga selalu membawa surat rahasia saat hujan turun deras.",
    "Penulis novel asyik bermain nasi goreng dengan perasaan gembira.",
    "Koki handal ingin meminjam nasi goreng di tengah hutan belantara.",
    "Kucing tetangga sedang menunggu gitar listrik di atas meja makan.",
    "Murid teladan sudah membeli kamera digital pada pagi hari yang cerah.",
    "Koki handal diam-diam memakan boneka beruang dengan perasaan gembira.",
    "Dokter gigi sudah membeli mobil balap di pinggir pantai yang indah.",
    "Adik saya sedang memperbaiki piring terbang untuk persiapan ujian nasional.",
]

words = [
    "Alpukat",
    "Ambil",
    "Anggur",
    "Angin",
    "Angsa",
    "Anjing",
    "Apel",
    "Apotek",
    "Awan",
    "Ayam",
    "Baca",
    "Badak",
    "Bagus",
    "Baju",
    "Bandara",
    "Bank",
    "Baru",
    "Bawa",
    "Bayam",
    "Bayar",
    "Bebek",
    "Becak",
    "Beli",
    "Besar",
    "Bintang",
    "Brokoli",
    "Buang",
    "Buaya",
    "Buka",
    "Bukit",
    "Bulan",
    "Burung",
    "Bus",
    "Cabai",
    "Cantik",
    "Cari",
    "Celana",
    "Cepat",
    "Cicak",
    "Cuci",
    "Danau",
    "Dekat",
    "Dinding",
    "Dokter",
    "Dompet",
    "Dosen",
    "Duduk",
    "Durian",
    "Gajah",
    "Gambar",
    "Ganteng",
    "Garpu",
    "Gelas",
    "Gereja",
    "Guling",
    "Gunung",
    "Guru",
    "Hamster",
    "Harimau",
    "Hotel",
    "Hujan",
    "Hutan",
    "Ikan",
    "Indah",
    "Jauh",
    "Jeep",
    "Jelek",
    "Jembatan",
    "Jendela",
    "Jerapah",
    "Kangkung",
    "Kantor",
    "Kapal",
    "Kasur",
    "Kebun",
    "Kecil",
    "Kelapa",
    "Kelinci",
    "Keluar",
    "Kentang",
    "Kerbau",
    "Kereta",
    "Koki",
    "Kol",
    "Komodo",
    "Kompor",
    "Komputer",
    "Kuat",
    "Kucing",
    "Kuda",
    "Kuil",
    "Kursi",
    "Labu",
    "Lalat",
    "Lama",
    "Lampu",
    "Langit",
    "Lantai",
    "Laptop",
    "Lari",
    "Laut",
    "Lebah",
    "Lemah",
    "Lemari",
    "Lembah",
    "Lompat",
    "Luas",
    "Mahal",
    "Makan",
    "Malas",
    "Mangga",
    "Manggis",
    "Marmut",
    "Masak",
    "Masinis",
    "Masjid",
    "Masuk",
    "Matahari",
    "Meja",
    "Melon",
    "Merpati",
    "Minum",
    "Mobil",
    "Monyet",
    "Motor",
    "Murah",
    "Musang",
    "Naik",
    "Nanas",
    "Nyamuk",
    "Nyanyi",
    "Pagar",
    "Panci",
    "Panda",
    "Panjang",
    "Pantai",
    "Pasar",
    "Pel",
    "Pelabuhan",
    "Pendek",
    "Pepaya",
    "Perahu",
    "Pesawat",
    "Pilot",
    "Pintar",
    "Pintu",
    "Piring",
    "Pisang",
    "Pisau",
    "Rajin",
    "Rakun",
    "Rambutan",
    "Rendah",
    "Rubah",
    "Rumah",
    "RumahSakit",
    "Rusa",
    "Sakit",
    "Salak",
    "Sandal",
    "Sapi",
    "Sapu",
    "Sawah",
    "Sawi",
    "Sedan",
    "Sekolah",
    "Semangka",
    "Semut",
    "Sendok",
    "Sepeda",
    "Singa",
    "Sopir",
    "Stasiun",
    "Sungai",
    "Suster",
    "Taman",
    "Tas",
    "Telepon",
    "Televisi",
    "Temu",
    "Tentara",
    "Terminal",
    "Terong",
    "Tiang",
    "Tidur",
    "Tikus",
    "Tinggi",
    "Tokek",
    "Toko",
    "Tomat",
    "Topi",
    "Truk",
    "Tulis",
    "Turun",
    "Tutup",
    "Ular",
    "Wajan",
    "Warung",
    "Wortel",
    "Zebra",
]
